development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: f041add4d8c27eca8bc239e375f89442ea14eae4abec31dc47a73308b4175cb6a12ab2e4eb0ed84401c565e32c2cef35874e0fd132f1826c1e004a37bc307748
